project:
  name: cocos-boilerplate
  team: games
  type: fe
  repo_path: https://git.garena.com/shopee/shopee-id/cocos-boilerplate

domain:
  path: /cocos-boilerplate
  prefix: play

dependencies:
  micro_fe: false
  pubsub: false
  gcs: false
