project:
  name: cocos-snake
  team: games
  type: fe
  repo_path: https://github.com/Haelinythii/cocos-snake

domain:
  path: /cocos-snake
  prefix: play

dependencies:
  micro_fe: false
  pubsub: false
  gcs: false
